steps:

# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'Backend/new_testprojectADO'
  args:
    [
      'build',
      '-t',
      'asia-south2-docker.pkg.dev/project-511e3fcc-1e7b-40fd-a5c/employee-repo/employee-api',
      '.'
    ]

# Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'asia-south2-docker.pkg.dev/project-511e3fcc-1e7b-40fd-a5c/employee-repo/employee-api'
    ]

images:
- 'asia-south2-docker.pkg.dev/project-511e3fcc-1e7b-40fd-a5c/employee-repo/employee-api'

options:
  logging: CLOUD_LOGGING_ONLY